//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiguous identifier detected.
        /// </summary>
        internal static string ambiguous_id {
            get {
                return ResourceManager.GetString("ambiguous_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Error.
        /// </summary>
        internal static string api_error {
            get {
                return ResourceManager.GetString("api_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string change_password {
            get {
                return ResourceManager.GetString("change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change your password fill in the fields below.
        /// </summary>
        internal static string change_password_text {
            get {
                return ResourceManager.GetString("change_password_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string change_password_title {
            get {
                return ResourceManager.GetString("change_password_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm code.
        /// </summary>
        internal static string confirm_code {
            get {
                return ResourceManager.GetString("confirm_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current  password.
        /// </summary>
        internal static string current_password {
            get {
                return ResourceManager.GetString("current_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid current password.
        /// </summary>
        internal static string current_password_invalid {
            get {
                return ResourceManager.GetString("current_password_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter sent code in the field below.
        /// </summary>
        internal static string enter_code {
            get {
                return ResourceManager.GetString("enter_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity not found.
        /// </summary>
        internal static string entity_not_found {
            get {
                return ResourceManager.GetString("entity_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session has expired.
        /// </summary>
        internal static string expired_session {
            get {
                return ResourceManager.GetString("expired_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        internal static string fail {
            get {
                return ResourceManager.GetString("fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        internal static string good {
            get {
                return ResourceManager.GetString("good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error.
        /// </summary>
        internal static string internal_error {
            get {
                return ResourceManager.GetString("internal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inválid code.
        /// </summary>
        internal static string invalid_code {
            get {
                return ResourceManager.GetString("invalid_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid http method.
        /// </summary>
        internal static string invalid_http_method {
            get {
                return ResourceManager.GetString("invalid_http_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid method.
        /// </summary>
        internal static string invalid_method {
            get {
                return ResourceManager.GetString("invalid_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid module.
        /// </summary>
        internal static string invalid_module {
            get {
                return ResourceManager.GetString("invalid_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid session, restart the process.
        /// </summary>
        internal static string invalid_session {
            get {
                return ResourceManager.GetString("invalid_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string loading_mobile {
            get {
                return ResourceManager.GetString("loading_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string login_forgot {
            get {
                return ResourceManager.GetString("login_forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string login_log {
            get {
                return ResourceManager.GetString("login_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string login_password {
            get {
                return ResourceManager.GetString("login_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover password.
        /// </summary>
        internal static string login_recover_btn_recover {
            get {
                return ResourceManager.GetString("login_recover_btn_recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username or email to reset your password.
        /// </summary>
        internal static string login_recover_message {
            get {
                return ResourceManager.GetString("login_recover_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover password.
        /// </summary>
        internal static string login_recover_title {
            get {
                return ResourceManager.GetString("login_recover_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email.
        /// </summary>
        internal static string login_user_name {
            get {
                return ResourceManager.GetString("login_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log not found.
        /// </summary>
        internal static string log_not_found {
            get {
                return ResourceManager.GetString("log_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowercase Letters.
        /// </summary>
        internal static string lowercase {
            get {
                return ResourceManager.GetString("lowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string new_password {
            get {
                return ResourceManager.GetString("new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password confirmation.
        /// </summary>
        internal static string new_password_confirm {
            get {
                return ResourceManager.GetString("new_password_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter sent code in the field below.
        /// </summary>
        internal static string new_password_title {
            get {
                return ResourceManager.GetString("new_password_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New recovery code generated.
        /// </summary>
        internal static string new_recovery_code {
            get {
                return ResourceManager.GetString("new_recovery_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function not yet implemented.
        /// </summary>
        internal static string not_implemented {
            get {
                return ResourceManager.GetString("not_implemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers.
        /// </summary>
        internal static string numbers {
            get {
                return ResourceManager.GetString("numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Characters.
        /// </summary>
        internal static string number_char {
            get {
                return ResourceManager.GetString("number_char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected option not found.
        /// </summary>
        internal static string option_not_found {
            get {
                return ResourceManager.GetString("option_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ou.
        /// </summary>
        internal static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been updated.
        /// </summary>
        internal static string password_changed_sucessfully {
            get {
                return ResourceManager.GetString("password_changed_sucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This process can take several minutes, please be patient. &lt;br /&gt;&lt;br /&gt; This window can be closed since this update occurs in the background..
        /// </summary>
        internal static string password_changed_text {
            get {
                return ResourceManager.GetString("password_changed_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must meet complexity requirements.
        /// </summary>
        internal static string password_complexity {
            get {
                return ResourceManager.GetString("password_complexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has expired and must be changed.
        /// </summary>
        internal static string password_expired_text {
            get {
                return ResourceManager.GetString("password_expired_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password should not contain your name as its part.
        /// </summary>
        internal static string password_name_part {
            get {
                return ResourceManager.GetString("password_name_part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Password confirmation are not equal.
        /// </summary>
        internal static string password_not_equal {
            get {
                return ResourceManager.GetString("password_not_equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Strength.
        /// </summary>
        internal static string password_strength {
            get {
                return ResourceManager.GetString("password_strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string return_default {
            get {
                return ResourceManager.GetString("return_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a option.
        /// </summary>
        internal static string select_option {
            get {
                return ResourceManager.GetString("select_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send code.
        /// </summary>
        internal static string send_code {
            get {
                return ResourceManager.GetString("send_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send the confirmation code to:.
        /// </summary>
        internal static string send_conf_to {
            get {
                return ResourceManager.GetString("send_conf_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong.
        /// </summary>
        internal static string strong {
            get {
                return ResourceManager.GetString("strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols.
        /// </summary>
        internal static string symbols {
            get {
                return ResourceManager.GetString("symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to systems.
        /// </summary>
        internal static string system_login_list {
            get {
                return ResourceManager.GetString("system_login_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the received code.
        /// </summary>
        internal static string type_code {
            get {
                return ResourceManager.GetString("type_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the password.
        /// </summary>
        internal static string type_password {
            get {
                return ResourceManager.GetString("type_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the password confirmation.
        /// </summary>
        internal static string type_password_confirm {
            get {
                return ResourceManager.GetString("type_password_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the current password.
        /// </summary>
        internal static string type_password_current {
            get {
                return ResourceManager.GetString("type_password_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow.
        /// </summary>
        internal static string unknow {
            get {
                return ResourceManager.GetString("unknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppercase Letters.
        /// </summary>
        internal static string uppercase {
            get {
                return ResourceManager.GetString("uppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User locked, contact system administrator.
        /// </summary>
        internal static string user_locked {
            get {
                return ResourceManager.GetString("user_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User logged from.
        /// </summary>
        internal static string user_logged {
            get {
                return ResourceManager.GetString("user_logged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string user_not_found {
            get {
                return ResourceManager.GetString("user_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid username or e-mail.
        /// </summary>
        internal static string valid_username {
            get {
                return ResourceManager.GetString("valid_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid username and password.
        /// </summary>
        internal static string valid_username_pwd {
            get {
                return ResourceManager.GetString("valid_username_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Strong.
        /// </summary>
        internal static string very_strong {
            get {
                return ResourceManager.GetString("very_strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Weak.
        /// </summary>
        internal static string very_weak {
            get {
                return ResourceManager.GetString("very_weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak.
        /// </summary>
        internal static string weak {
            get {
                return ResourceManager.GetString("weak", resourceCulture);
            }
        }
    }
}
